---
name: Run Maestro with srcpy

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  run-with-video-recording:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

#      - name: Setup Android SDK
#        if: steps.avd-cache.outputs.cache-hit != 'true'
#        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30-toto-${{ runner.os }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          cores: 4
          ram-size: 8192M
          heap-size: 8192
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Cache scrcpy
        id: scrcpy-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/scrcpy
          key: scrcpy-${{ runner.os }}-${{ hashFiles('**/scrcpy') }}
          restore-keys: |
            scrcpy-${{ runner.os }}-

      - name: Install scrpy
        if: steps.scrcpy-cache.outputs.cache-hit != 'true'
        run: |
          # for Debian/Ubuntu
          sudo apt install ffmpeg libsdl2-2.0-0 adb wget \
                gcc git pkg-config meson ninja-build libsdl2-dev \
                libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                libswresample-dev libusb-1.0-0 libusb-1.0-0-dev
          
          git clone https://github.com/Genymobile/scrcpy
          cd scrcpy
          ./install_release.sh
          
          whereis scrcpy
          scrcpy --version
          

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          cores: 4
          ram-size: 8192M
          heap-size: 8192
          api-level: 30
          target: google_apis
          arch: x86
          force-avd-creation: false
          emulator-options: -verbose -memory 16384 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          profile: pixel_6
          disable-animations: true
          script: |
            #!/bin/sh
            set +e
            
            echo $DISPLAY
            
            adb devices
            
            scrcpy -s emulator-5554 --no-audio --record=file.mkv
  
            adb shell "ls -ld /sdcard"
            
            sleep 15  # Ajuste la durée de l'enregistrement
            
            pkill scrcpy
            
            echo "ok"
            


      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-report
          path: |
            output.mkv
