---
name: Run Maestro with srcpy

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  run-with-video-recording:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install srcpy
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y scrcpy
          whereis scrcpy

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Cache Maestro
#        id: maestro-cache
#        uses: actions/cache@v4
#        with:
#          path: ~/.maestro/bin/maestro
#          key: maestro-${{ runner.os }}-${{ hashFiles('**/maestro') }}
#          restore-keys: |
#            maestro-${{ runner.os }}-
#
#      - name: Install Maestro
#        if: steps.maestro-cache.outputs.cache-hit != 'true'
#        run: |
#          curl -Ls "https://get.maestro.mobile.dev" | bash
#          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Android SDK
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29-${{ runner.os }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          cores: 8
          ram-size: 9000M
          heap-size: 8192
          api-level: 29
          force-avd-creation: false
          emulator-options: -verbose -memory 16384 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          profile: pixel_6
          disable-animations: true
          script: |
            #!/bin/sh
            set +e
            
            export DISPLAY=:1
            scrcpy --record output.mp4 &
            adb shell input keyevent 82 &
            sleep 15  # Ajuste la durée de l'enregistrement
            pkill scrcpy  # Stopper scrcpy après l'enregistrement
      
            echo "ok"



      - name: Upload Maestro artifacts (report/video)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: maestro-report
          path: |
            screenshot.png
            maestro-report.xml
            screenrecord.mp4
            output.mp4
#            maestro test android-lbc-ad-insertion.yaml --format junit --output maestro-report.xml
#             adb shell monkey -p fr.leboncoin.delivery -c android.intent.category.LAUNCHER 1
